--- Makefile-original	2014-10-07 15:15:19.000000000 +0900
+++ Makefile-updated	2014-10-07 15:16:15.000000000 +0900
@@ -5,6 +5,7 @@
 #
 Version = 1.4.2
 PKGNAME = jpegoptim
+PKGLIB = libjpegoptim.a
 
 SHELL = /bin/sh
 
@@ -58,7 +59,10 @@
 $(PKGNAME):	$(OBJS) 
 	$(CC) $(CFLAGS) -o $(PKGNAME) $(OBJS) $(LDFLAGS) $(LIBS) 
 
-all:	$(PKGNAME) 
+$(PKGLIB): $(OBJS)
+	ar crsv $(PKGLIB) $(OBJS)
+
+all:	$(PKGNAME) $(PKGLIB)
 
 strip:
 	for i in $(PKGNAME) ; do [ -x $$i ] && $(STRIP) $$i ; done
